version: '3.8'

services:
  web:
    image: php:8.1-apache # Uses the official PHP 8.1 image with Apache
    container_name: php_apache_app
    ports:
      - "80:80" # Maps port 80 on your host to port 80 in the container
    volumes:
      - ./php_app:/var/www/html # Mounts your local 'php_app' directory into the container's web root
    depends_on:
      - db # Ensures the 'db' service starts before 'web'
    environment:
      # These are examples; adjust as needed for your PHP application
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase

  db:
    image: mysql:8.0 # Uses the official MySQL 8.0 image
    container_name: mysql_database
    ports:
      - "3306:3306" # Maps port 3306 on your host to port 3306 in the container
    environment:
      MYSQL_ROOT_PASSWORD: root_password # IMPORTANT: Change this in production
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql # Persists MySQL data to a named volume

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest # Uses the official phpMyAdmin image
    container_name: phpmyadmin_interface
    ports:
      - "8080:80" # Maps port 8080 on your host to port 80 in the phpMyAdmin container
    environment:
      PMA_HOST: db # Connects phpMyAdmin to the 'db' service
      MYSQL_ROOT_PASSWORD: root_password # Use the same root password as your MySQL service
    depends_on:
      - db # Ensures the 'db' service starts before 'phpmyadmin'

volumes:
  db_data: # Defines the named volume for MySQL data persistence